#!/bin/bash

# load variables
source temp/variables

if [ "$1" != "Original" ] && [ "$1" != "Rebuild" ] && [ "$1" != "Updated" ]; then
    echo "Usage: ./update-db [Original, Rebuild, Updated] [Original, Rebuild, Updated]"
    exit 1
fi

if [ "$2" != "Original" ] && [ "$2" != "Rebuild" ] && [ "$2" != "Updated" ]; then
    echo "Usage: ./update-db [Original, Rebuild, Updated] [Original, Rebuild, Updated]"
    exit 1
fi

# compare datasets
cd "$path_to_jena_bin"
./rdfcompare http://localhost:3030/$1 http://localhost:3030/$2