#!/bin/bash

# variables
instances=instances.stottr
templates=person.stottr
output=output.ttl
dataset_name=Person

#paths
path_to_db=/home/magnus/Emner/Master/apache-jena-fuseki-4.5.0

# Create rdf file with lutra
java -jar lutra.jar --mode expand --library "$templates" --libraryFormat stottr --inputFormat stottr "$instances" -o "$output"

# create datasets if not defined and load data after server is started
sleep 4 &&
curl --location --request POST 'http://localhost:3030/$/datasets?dbName=Original&dbType=mem' &&

curl --location --request POST 'http://localhost:3030/$/datasets?dbName=Rebuild&dbType=mem' &&

curl --location --request POST 'http://localhost:3030/$/datasets?dbName=Updated&dbType=mem' &&

curl --location --request PUT 'http://localhost:3030/Original' \
--header 'Content-Type: text/turtle' \
--data-binary '@/home/magnus/Emner/Master/Test/output.ttl'&

# start fuseki-server on port 3030
cp "$output" "$path_to_db"
cd "$path_to_db"
./fuseki-server --update 

