#!/bin/bash

# load variables
source temp/variables

if [ "$1" != "Original" ] && [ "$1" != "Rebuild" ] && [ "$1" != "Updated" ]; then
    echo "Usage: ./update-db [Original, Rebuild, Updated]"
    exit 1
fi

"$path_to_bin"/s-update --service=http://localhost:$port/$1 --update="$temp_files/$updateQuery"
"$path_to_bin"/s-query --service=http://localhost:$port/$1 --query="$temp_files/$query"

