#!/bin/bash

# load variables
source temp/variables

# update Updated dataset
"$path_to_bin"/s-update --service=http://localhost:3030/Updated --update="$temp_files/$updateQuery"

# update Rebuild dataset
cd "$temp_files"
java -jar "$lutra" --mode expand --library "$templates" --libraryFormat stottr --inputFormat stottr "$instances" -o "$rebuildOutput"

# insert data into rebuild dataset
curl --location --request PUT 'http://localhost:3030/Rebuild' \
--header 'Content-Type: text/turtle' \
--data-binary "@$temp_files/$rebuildOutput"&