#!/bin/bash

# paths
path_to_db="/home/prebz/ottr/apache-jena-fuseki-4.5.0"
temp_files="/home/prebz/ottr/dev/temp"
path_to_bin="/home/prebz/ottr/apache-jena-fuseki-4.5.0/bin"
path_to_jena_bin="/home/prebz/ottr/apache-jena-4.6.0/bin"
lutra="/home/prebz/ottr/lutra/lutra-cli/target/lutra.jar"
# variables
instances=instances.stottr
templates=templates.stottr
output=output.ttl
rebuildOutput=rebuildOutput.ttl
query=query.rq
updateQuery=updateQuery.rq